### PR TITLE
Add secretsgen-controller chart (v0.16.0)

### PR DESCRIPTION
**Pull request by gtirloni**
To migrate to the Helm chart:

```
kubectl delete ns secretgen-controller
ansible-playbook -t secretgen-controller playbooks/site.yml
```

logs should show it detected all the certificates and other resources it manages.

### CODE REVIEW

**Review by mnaser — CHANGES_REQUESTED** [review]
I think we need to handle upgrade impact, because I think Helm will give errors if the resource already exists.

**Comment by gtirloni** [comment]
> I think we need to handle upgrade impact, because I think Helm will give errors if the resource already exists.

would it be okay to have a task to delete the secretgen-operator namespace in this case? that's what i did in my tests and it works fine

**Comment by mnaser** [comment]
Sure, but then it would delete it and redeploy on every single run so we just have to accommodate for that :)

**Comment by gtirloni** [comment]
> Sure, but then it would delete it and redeploy on every single run so we just have to accommodate for that :)

I added a task that ensures the secretgen-controller namespace is absent. I think that should do it.

I actually moved the controller into the kube-system together with other cluster-wide services. I think that's what you might mean with with things getting redeployed (that is, if they were in the original namespace)?

I think there's no practical requirement to have a separate namespace for this, that's why I moved it.

**Comment by gtirloni** [comment]
Related #1368

**Pull request closed without merging**
