### PR TITLE
Fix multipathd ppa install failure in non Ubuntu Jammy release

### LINKED ISSUE #1574: multipathd ppa only for Jammy
The current [PPA](https://github.com/vexxhost/atmosphere/blob/main/roles/multipathd/defaults/main.yml#L23) is only for Jammy.

Our current Computes are on Focal. Would be create if you also add the Jammy packages.

### PR DESCRIPTION
**Pull request by yaguangtang**
Closes #1574

### CODE REVIEW

**Comment by mpiscaer** [comment]
LGTM

**Comment by mnaser** [comment]
regate

**Pull request merged**
