### PR TITLE
[tox] Add toml as dependency for molecule

### PR DESCRIPTION
**Pull request by okozachenko1203**

### CODE REVIEW

**Comment by mnaser** [comment]
@okozachenko1203 hmm, I've only been using `poetry` to run this, let me think about this. bit more.

**Comment by mpiscaer** [comment]
This was needed for me inside the venv on Focal.

**Comment by mnaser** [comment]
> This was needed for me inside the Tox venv on Focal.

indeed, but we've shifted things towards Poetry (granted, we haven't actually properly and cleanly documented the switch over).

I'll follow this up with some changes to docs as well as removing the leftover `tox` stuff, Poetry is much nicer to work with overall.

**Comment by mnaser** [comment]
tox.ini is gone!

**Pull request closed without merging**
