### PR TITLE
[ATMOSPHERE-595] update libvirt-tls-sidecar image tag to latest

### PR DESCRIPTION
**Pull request by yaguangtang**
Depends-On: https://github.com/vexxhost/atmosphere/pull/2150

### CODE REVIEW

**Review by mnaser — CHANGES_REQUESTED** [review]
@yaguangtang can you also drop/remove all the existing libvirt jobs, all the existing libvirt code, etc?

**Comment by mnaser** [comment]
recheck

**Comment by yaguangtang** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Pull request merged**
