### PR TITLE
feat: switch to binary runc and containerd install

### PR DESCRIPTION
**Pull request by fitbeard**
- add multipurpose `binary_download` role
- add`runc` role 
- rewrite `containerd` role and switch to binary installation
- add better and more detailed version control support for Atmosphere components

This also introduces first batch of changes required for multi Linux distribution support https://github.com/vexxhost/atmosphere/issues/184

### CODE REVIEW

**Comment by mnaser** [comment]
@fitbeard this is really neat, I have a few questions if you don't mind me asking:

- What happens when you are running this on an existing deployment of Atmosphere?  When those binaries disappear or the services get related, do things go bork?
- Do you think it's possible for you to create a Molecule scenario which uses Docker that runs for both CentOS/RHEL & Ubuntu only for testing the containerd/runc roles?  It feels like it would be good to have that (at least for the components that are OS-specific) and those can run quickly on a separate molecule scenario (similar to image_manifest)

Thoughts?

**Comment by mnaser** [comment]
Also I'm curious if there is any reasoning behind why you're pulling into the Ansible controller and then uploading again, we've been more on the behaviour of pulling directly into the control plane nodes and avoiding things to be on the Ansible controller

**Comment by fitbeard** [comment]
> Also I'm curious if there is any reasoning behind why you're pulling into the Ansible controller and then uploading again, we've been more on the behaviour of pulling directly into the control plane nodes and avoiding things to be on the Ansible controller

Fixed. Now working on molecule part.

**Comment by fitbeard** [comment]
> @fitbeard this is really neat, I have a few questions if you don't mind me asking:
> 
>     * What happens when you are running this on an existing deployment of Atmosphere?  When those binaries disappear or the services get related, do things go bork?
> 
I tried the `containerd` installed with the package manager by replacing it with a binary and restarting the service. All the containers on the hosts seem to be operational. So I think the behavior is the same as if it was updated by the package manager.
>     * Do you think it's possible for you to create a Molecule scenario which uses Docker that runs for both CentOS/RHEL & Ubuntu only for testing the containerd/runc roles?  It feels like it would be good to have that (at least for the components that are OS-specific) and those can run quickly on a separate molecule scenario (similar to image_manifest)
> 
> 
> Thoughts?

@mnaser I added needed molecule tests. Also additional role for `crictl` <- later I plan to start refactoring `kubernetes`. Right now `crictl` role is only used for this molecule scenario.

**Comment by mnaser** [comment]
i tested on my side, things seem fine, nothing happened running this on a prod cluster.

**Pull request merged**
