### PR TITLE
fix: add fix for designate db

### PR DESCRIPTION
**Pull request by ricolin**
This introduce DB fix from:
https://review.opendev.org/c/openstack/designate/+/910322

fix https://github.com/vexxhost/atmosphere/issues/985

### CODE REVIEW

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
regate

**Comment by mnaser** [comment]
recheck

**Comment by ricolin** [comment]
recheck

**Comment by mnaser** [comment]
regate

**Comment by mnaser** [comment]
regate

**Pull request merged**
