### PR TITLE
fix: use local patch for libvirt tls initContainer patch

### PR DESCRIPTION
**Pull request by okozachenko1203**
Depends-On: https://github.com/vexxhost/chart-vendor/pull/8

### CODE REVIEW

**Comment by yaguangtang** [comment]
recheck

**Comment by okozachenko1203** [comment]
depends-on: https://github.com/vexxhost/chart-vendor/pull/8

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Pull request merged**
