### PR TITLE
fix(neutron): Nit fix for config `neutron/ovn/enable_distributed_floating_ip`

### PR DESCRIPTION
**Pull request by ricolin**

### CODE REVIEW

**Review by mnaser — CHANGES_REQUESTED** [review]
@ricolin We have explicitly disabled this because it has caused us a lot of network connectivity issues, i think it's not a very stable feature for now unfortunately.

**Comment by ricolin** [comment]
@mnaser why this can't be disabled from roles? https://github.com/vexxhost/atmosphere/pull/680/commits/429020d9032dd3197fefc47c2d1c9fe800f7716f#diff-1c5c2ad5f0f97e5d10ff8f9d4cdf157e025be857679f01d78ac98891d293e063R79

**Comment by mnaser** [comment]
Oh I see. The charts default to true and we are forcing false. Ok good

**Comment by mnaser** [comment]
Can you re-open a new PR please?

**Pull request closed without merging**
