### PR TITLE
feat: add rook-ceph

### PR DESCRIPTION
**Pull request by guilhermesteinmuller**
Fixes https://github.com/vexxhost/atmosphere/pull/131

### CODE REVIEW

**Comment by mnaser** [comment]
@guilhermesteinmuller this looks good initially, I'm doing some work here in #125 that I'd like to land first and once that is done I'll rebase your work on top of that

**Comment by guilhermesteinmuller** [comment]
this is what ive got so far

```
root@ctl1:~# kubectl -n rook-ceph get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/rook-ceph-operator-84f94576b-j4rbn   1/1     Running   0          3h17m

NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/rook-ceph-admission-controller   ClusterIP   10.104.176.202   <none>        443/TCP   3h15m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-operator   1/1     1            1           3h17m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/rook-ceph-operator-84f94576b   1         1         1       3h17m
```

**Comment by mnaser** [comment]
so the only thing this branch needs is the ability to create endpoints/users for rgw, since I tested the 'manual' steps and it works just fine.

**Comment by thywyn** [comment]
@mnaser Looking at this a little closer why aren't we removing the ceph provisioner helm chart and enabling the rook csi rbd driver? Are we just trying to add the RGW without too many changes outside of the operator? If you do move CSI to Rook then all you'd need to add are the service and endpoint objects for the ceph cluster, yes?

**Pull request closed without merging**
