### PR TITLE
[stable/zed] Stop using CDN for CI (#2185)

### LINKED ISSUE #2190: [stable/zed] Stop using CDN for CI
Manual cherrypick required.

#2185 failed to apply on top of branch "stable/zed":
```
Applying: Switch image builds to use Harbor
Using index info to reconstruct a base tree...
M	images/barbican/Dockerfile
M	images/cinder/Dockerfile
M	images/designate/Dockerfile
M	images/glance/Dockerfile
M	images/heat/Dockerfile
M	images/horizon/Dockerfile
M	images/ironic/Dockerfile
M	images/keepalived/Dockerfile
M	images/keystone/Dockerfile
M	images/libvirtd/Dockerfile
M	images/magnum/Dockerfile
M	images/manila/Dockerfile
M	images/netoffload/Dockerfile
M	images/neutron/Dockerfile
M	images/nova-ssh/Dockerfile
M	images/nova/Dockerfile
M	images/octavia/Dockerfile
M	images/openstack-runtime/Dockerfile
M	images/openstack-venv-builder/Dockerfile
M	images/ovn/Dockerfile
M	images/placement/Dockerfile
M	images/python-base/Dockerfile
M	images/python-openstackclient/Dockerfile
M	images/staffeln/Dockerfile
M	images/tempest/Dockerfile
M	images/ubuntu-cloud-archive/Dockerfile
Falling back to patching base and 3-way merge...
Auto-merging images/ubuntu-cloud-archive/Dockerfile
Auto-merging images/tempest/Dockerfile
CONFLICT (content): Merge conflict in images/tempest/Dockerfile
Auto-merging images/staffeln/Dockerfile
Auto-merging images/python-openstackclient/Dockerfile
Auto-merging images/python-base/Dockerfile
Auto-merging images/placement/Dockerfile
CONFLICT (content): Merge conflict in images/placement/Dockerfile
Auto-merging images/ovn/Dockerfile
Auto-merging images/openstack-venv-builder/Dockerfile
CONFLICT (content): Merge conflict in images/openstack-venv-builder/Dockerfile
Auto-merging images/openstack-runtime/Dockerfile
Auto-merging images/octavia/Dockerfile
CONFLICT (content): Merge conflict in images/octavia/Dockerfile
Auto-merging images/nova/Dockerfile
CONFLICT (content): Merge conflict in images/nova/Dockerfile
Auto-merging images/nova-ssh/Dockerfile
Auto-merging images/neutron/Dockerfile
CONFLICT (content): Merge conflict in images/neutron/Dockerfile
Auto-merging images/netoffload/Dockerfile
Auto-merging images/manila/Dockerfile
CONFLICT (content): Merge conflict in images/manila/Dockerfile
Auto-merging images/magnum/Dockerfile
CONFLICT (content): Merge conflict in images/magnum/Dockerfile
Auto-merging images/libvirtd/Dockerfile
Auto-merging images/keystone/Dockerfile
CONFLICT (content): Merge conflict in images/keystone/Dockerfile
Auto-merging images/keepalived/Dockerfile
Auto-merging images/ironic/Dockerfile
CONFLICT (content): Merge conflict in images/ironic/Dockerfile
Auto-merging images/horizon/Dockerfile
CONFLICT (content): Merge conflict in images/horizon/Dockerfile
Auto-merging images/heat/Dockerfile
CONFLICT (content): Merge conflict in images/heat/Dockerfile
Auto-merging images/glance/Dockerfile
CONFLICT (content): Merge conflict in images/glance/Dockerfile
Auto-merging images/designate/Dockerfile
CONFLICT (content): Merge conflict in images/designate/Dockerfile
Auto-merging images/cinder/Dockerfile
CONFLICT (content): Merge conflict in images/cinder/Dockerfile
Auto-merging images/barbican/Dockerfile
CONFLICT (content): Merge conflict in images/barbican/Dockerfile
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Switch image builds to use Harbor
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by yaguangtang**
Switch image builds to use Harbor
Switch Zuul to avoid CDN
Small more fixes
Configure CI bits to not use CDN
fixes #2190

### CODE REVIEW

**Comment by mnaser** [comment]
regate

**Comment by mnaser** [comment]
regate

**Comment by yaguangtang** [comment]
regate

**Comment by yaguangtang** [comment]
regate

**Pull request merged**
