### PR TITLE
chore: tunning cinder encrypted volume create

### PR DESCRIPTION
**Pull request by ricolin**
ref https://review.opendev.org/c/openstack/cinder/+/910700

### CODE REVIEW

**Comment by mnaser** [comment]
@ricolin looks good overall but I don't think smoke tests include Barbican. 

Did you validate the patch inside DevStack for example or in a test environment locally?

**Comment by ricolin** [comment]
> @ricolin looks good overall but I don't think smoke tests include Barbican.
> 
> Did you validate the patch inside DevStack for example or in a test environment locally?

Yeah, validated encrypted volume with both devstack and a local atmosphere aio env

**Comment by ricolin** [comment]
relate to https://github.com/vexxhost/atmosphere/issues/1016

**Comment by mnaser** [comment]
We'll backport this for customers and then just wait for the backport to land upstream

**Pull request closed without merging**
