### PR TITLE
Update kube-prometheus-stack to 58.1.3

### PR DESCRIPTION
**Pull request by gtirloni**
This is needed to fix false positives for missing kube-scheduler, etc.

### CODE REVIEW

**Comment by gtirloni** [comment]
> Can you also run:
> 
> tox -e sync-charts

```
$ tox -e sync-charts
sync-charts: install_deps> python -I -m pip install aiopath aioshutil asynctempfile GitPython platformdirs pydantic pydantic-yaml python-gerrit-api
.pkg: install_requires> python -I -m pip install 'poetry-core>=1.0.0' poetry-dynamic-versioning
.pkg: _optional_hooks> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True poetry_dynamic_versioning.backend
.pkg: get_requires_for_build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True poetry_dynamic_versioning.backend
.pkg: build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True poetry_dynamic_versioning.backend
sync-charts: install_package_deps> python -I -m pip install 'aiopath<0.8.0,>=0.7.7' 'aioshutil<2.0,>=1.3' 'ansible-core<3.0.0,>=2.15.9' 'asynctempfile<0.6.0,>=0.5.0' 'docker-image-py<0.2.0,>=0.1.12' 'gerrit<0.0.3,>=0.0.2' 'jmespath<2.0.0,>=1.0.1' 'netaddr<0.9.0,>=0.8.0' 'openstacksdk<0.99.0' 'rjsonnet<0.6.0,>=0.5.2'
sync-charts: install_package> python -I -m pip install --force-reinstall --no-deps /home/gtirloni/code/vexxhost/atmosphere/.tox/.tmp/package/1/atmosphere-1.10.4.post165.dev0+b29fca96-py3-none-any.whl
sync-charts: commands[0]> python3 /home/gtirloni/code/vexxhost/atmosphere/build/sync-charts.py
Traceback (most recent call last):
  File "/home/gtirloni/code/vexxhost/atmosphere/build/sync-charts.py", line 25, in <module>
    from gerrit import GerritClient
  File "/home/gtirloni/code/vexxhost/atmosphere/.tox/sync-charts/lib/python3.12/site-packages/gerrit/__init__.py", line 1, in <module>
    from gerrit import rpc, error
  File "/home/gtirloni/code/vexxhost/atmosphere/.tox/sync-charts/lib/python3.12/site-packages/gerrit/rpc.py", line 7, in <module>
    from gerrit import model, error, decode, service
  File "/home/gtirloni/code/vexxhost/atmosphere/.tox/sync-charts/lib/python3.12/site-packages/gerrit/service.py", line 4, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
sync-charts: exit 1 (0.09 seconds) /home/gtirloni/code/vexxhost/atmosphere> python3 /home/gtirloni/code/vexxhost/atmosphere/build/sync-charts.py pid=192221
.pkg: _exit> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True poetry_dynamic_versioning.backend
  sync-charts: FAIL code 1 (16.87=setup[16.78]+cmd[0.09] seconds)
  evaluation failed :( (16.92 seconds)
```

**Comment by mnaser** [comment]
I think you've got too new of a Python! :P

**Review by mnaser — APPROVED** [review]

**Comment by gtirloni** [comment]
@mnaser even after installing pyenv and switch to python 3.10, tox was failing because it was trying to use python 3.12.

this was due to me having tox installed through system packages that used the system's python 3.12.

i removed the tox package and installed it again inside the python 3.10 pyenv environment. this time it worked.

**Pull request merged**
