### PR TITLE
feat: switch to binary kubernetes, fluxcd and helm install

### PR DESCRIPTION
**Pull request by fitbeard**
- rewrite `kubernetes` role and switch to binary installation
- rewrite `flux` role and switch to binary installation
- rewrite `helm` role and switch to binary installation
-  replace some verify tasks in `containerd` molecule tests to maker sure that `crictl` role works as expected 

This also introduces second batch of changes required for multi Linux distribution support https://github.com/vexxhost/atmosphere/issues/184

Tested on Ubutnu 20.04, Ubuntu 22.04, Rocky Linux 8, Rocky Linux 9

Off topic: It doesn't matter what `kubelet` or `contained` versions(latest) I try to use for `kubeadm init` on Rocky Linux 9 (kernel 5.14.x) - everything ends with random pod OOM.

### CODE REVIEW

**Comment by fitbeard** [comment]
Off topic #2: Please stop committing lint incompatible changes to main branch:)

**Comment by mnaser** [comment]
@fitbeard sorry for breakage, looking at this now, going to see at how we can do some more further tests too

**Comment by fitbeard** [comment]
@mnaser all good. About Rocky9 thingy - it's safe to ignore for now because something is much deeper:
- https://github.com/argoproj/argo-cd/issues/12289
- https://bugs.rockylinux.org/view.php?id=2576

**Comment by mnaser** [comment]
I'm calling it at this point.. there are a few outstanding things

- Debian doesn't start up in GHA, but works fine locally (no clue.. seeing `socket: permission denied`)
- RockyLinux 8 seems to complain about the Kubernetes Python package.. seems like a quick fix but I'm tired now :)

@fitbeard if you have sometime to look at it perhaps

**Comment by mnaser** [comment]
@fitbeard: nice!  that leaves us with only debian borked and adding the k8s-ha scenario.. i'll work on the latter cause i got incredibly frustrated doing the first :)

**Comment by mnaser** [comment]
aha...

```
[ 3388.798548] audit: type=1400 audit(1679079648.307:531): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48184 comm="kube-apiserver" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[ 3388.814114] audit: type=1400 audit(1679079648.323:532): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48196 comm="kube-controller" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[ 3388.843912] audit: type=1400 audit(1679079648.351:533): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48184 comm="kube-apiserver" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 3388.844051] audit: type=1400 audit(1679079648.351:534): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48184 comm="kube-apiserver" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 3388.844184] audit: type=1400 audit(1679079648.351:535): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48184 comm="kube-apiserver" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 3388.844289] audit: type=1400 audit(1679079648.351:536): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48184 comm="kube-apiserver" family="inet6" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[ 3388.862138] audit: type=1400 audit(1679079648.371:537): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48176 comm="kube-scheduler" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[ 3389.223275] audit: type=1400 audit(1679079648.731:538): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48196 comm="kube-controller" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[ 3389.479334] audit: type=1400 audit(1679079648.987:539): apparmor="DENIED" operation="create" profile="cri-containerd.apparmor.d" pid=48176 comm="kube-scheduler" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
```

**Comment by mnaser** [comment]
I think containerd support for Debian is broken right now, if it's the CI or the actual role itself, can't tell you..

I'll just drop the support for it since I'm pretty sure if we attempt to run a container it would fail.

**Comment by mnaser** [comment]
I refactored a bit part of your work into here:

https://github.com/vexxhost/ansible-collection-kubernetes

Next up, I just need to test what happens when a cluster is installed using packages and switched to binary, I'm concerned the `kubelet` service will be killed off.

I also need to add CSI support to that collection, but we'll be in good shape to merge this very soon.  I appreciate your patience.

**Comment by mnaser** [comment]
looks like it kills the whole node if we apt remove kubelet.. we're going to have to think about this

**Comment by mnaser** [comment]
https://askubuntu.com/a/117278 might be the way... it aint pretty though but it'll probably do the job..

**Comment by fitbeard** [comment]
@mnaser sorry, i've been afk for whole weekend. i'm looking right now in what you achieved here!

**Comment by fitbeard** [comment]
@mnaser i found why rhel9 family is crashing:

https://review.opendev.org/c/openstack/kolla-ansible/+/799229/53/ansible/group_vars/all.yml#184
https://github.com/containerd/containerd/issues/3201
https://github.com/containerd/containerd/pull/7566

Which place would be the best to document this? `atmosphere/docs` or `ansible-collection-kubernetes/xxx`

**Comment by fitbeard** [comment]
Or we should change atmospheres default `infinity` to something like `1048576`?

**Comment by fitbeard** [comment]
https://github.com/moby/moby/issues/38814

**Comment by mnaser** [comment]
@fitbeard: let's set it to 1048576 in the kubernetes repo

**Comment by mnaser** [comment]
@fitbeard: i created https://github.com/vexxhost/ansible-collection-kubernetes/issues/9 if you dont mind looking into that, i might be able to down the line if i find sometime

**Comment by fitbeard** [comment]
@mnaser boom https://github.com/vexxhost/ansible-collection-kubernetes/pull/10

**Comment by mnaser** [comment]
i think we're pretty close to landing this.. i am testing locally

**Pull request merged**
