### PR TITLE
Align horizon chart

### PR DESCRIPTION
**Pull request by KeplerSysAdmin**
- Update pymysql version info. Horizon requiers newer mysql client version than we had previously
- Update scripts to use sysconfig.get_path instead of distutils.sysconfig.get_python_lib which is deprecated

reference: https://review.opendev.org/c/openstack/openstack-helm/+/919778

### CODE REVIEW

**Comment by mnaser** [comment]
Can you please look into making those changes in the `.charts.yml` file, either as a patch or simply as a bump and then running `too -e sync-charts` in order to see things in sync?

Thanks for the contribution!

**Comment by KeplerSysAdmin** [comment]
> Can you please look into making those changes in the `.charts.yml` file, either as a patch or simply as a bump and then running `too -e sync-charts` in order to see things in sync?
> 
> Thanks for the contribution!

Align horizon chart version on file .chart.yml

**Comment by mnaser** [comment]
Did you make sure to run the sync after updating?  I doubt that there was no updates from .15 to .22 :)

**Comment by KeplerSysAdmin** [comment]
> Did you make sure to run the sync after updating? I doubt that there was no updates from .15 to .22 :)

I'm not sure what you mean.

**Comment by mnaser** [comment]
You will need to run `tox -e sync-charts` after making the change in charts which will resynchronize all the charts.

**Comment by KeplerSysAdmin** [comment]
Those are a lot unexpected changes:
Screenshot from 2024-05-30 23-26-40

**Comment by mnaser** [comment]
There shouldn't be that much changes if you run it, perhaps the process fails, do you have patch diff missing perhaps?

**Comment by KeplerSysAdmin** [comment]
Hi @mnaser 
Please close this ticket, it is aligned on tag v1.11.2 so this work is unnecessary

**Pull request closed without merging**
