### PR TITLE
[ATMOSPHERE-364] cert-manager: Add support for Azure DNS

### PR DESCRIPTION
**Pull request by gtirloni**

### CODE REVIEW

**Comment by gtirloni** [comment]
@guilhermesteinmuller could you help test this?

**Review by guilhermesteinmuller — COMMENTED** [review]
I am thinking now if we should support that. 

I had issues with DNSSEC: NSEC Missing: validation failure while attempting to issue the cert and it looks like azure dns doesnt support that...

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
regate

**Pull request merged**
