### PR TITLE
upgrade mcapi, k8s collection and capo version

### PR DESCRIPTION
**Pull request by okozachenko1203**
- mcapi 0.22.1 -> 0.24.0 https://github.com/vexxhost/magnum-cluster-api/releases/tag/v0.24.0
- k8s collection 0.14.3 -> 0.15.0 https://github.com/vexxhost/ansible-collection-kubernetes/releases/tag/v1.15.0

### CODE REVIEW

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
@okozachenko1203 i think we need to probably change the image tags

**Comment by okozachenko1203** [comment]
image
keycloak is unhealthy in CI

**Comment by mnaser** [comment]
It seems the CAPI controller is still 1.6.0 and it seems we're not even using the image we build for CAPO.

@okozachenko1203 I think maybe we should remove our build and go upstream only, so we can remove the extra job that's a bit useless :p

**Pull request merged**
