### PR TITLE
[ATMOSPHERE-553] Disable log config append

### PR DESCRIPTION
**Pull request by okozachenko1203**
- designate
- manila
- nova

Depends-on: https://github.com/vexxhost/atmosphere/pull/2087

### CODE REVIEW

**Comment by mnaser** [comment]
recheck

**Comment by okozachenko1203** [comment]
depends-on: https://github.com/vexxhost/atmosphere/pull/2087

**Comment by okozachenko1203** [comment]
recheck

**Comment by yaguangtang** [comment]
recheck

**Pull request merged**
